// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-coVJINBOV77dQ0euYvDbq1kmDnfsYzo',
    appId: '1:764836204733:web:6ca71de7bc55914c1127d4',
    messagingSenderId: '764836204733',
    projectId: 'flutter-chart-app-53d26',
    authDomain: 'flutter-chart-app-53d26.firebaseapp.com',
    storageBucket: 'flutter-chart-app-53d26.appspot.com',
    measurementId: 'G-TZQ0QRQEFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-hAP1TZgJI1LnLQ4Rp4yYwLLWgkodrOc',
    appId: '1:764836204733:android:e64679327cb3a9d21127d4',
    messagingSenderId: '764836204733',
    projectId: 'flutter-chart-app-53d26',
    storageBucket: 'flutter-chart-app-53d26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZYHYH7C-P9JB-u5v9mipdveew1GFHRd8',
    appId: '1:764836204733:ios:5e8aebf6a7890f831127d4',
    messagingSenderId: '764836204733',
    projectId: 'flutter-chart-app-53d26',
    storageBucket: 'flutter-chart-app-53d26.appspot.com',
    iosClientId: '764836204733-l41f3bunbhsvp8fdst02lv1t8h7in9u2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chart2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZYHYH7C-P9JB-u5v9mipdveew1GFHRd8',
    appId: '1:764836204733:ios:5e8aebf6a7890f831127d4',
    messagingSenderId: '764836204733',
    projectId: 'flutter-chart-app-53d26',
    storageBucket: 'flutter-chart-app-53d26.appspot.com',
    iosClientId: '764836204733-l41f3bunbhsvp8fdst02lv1t8h7in9u2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chart2',
  );
}
